services:
  pdf-watch:
    image: ghcr.io/yimengl/private-pdf-translator:latest
    command: watch /data
    volumes:
      - ${WATCH_FOLDER}:/data
    environment:
      - ANTHROPIC_API_KEY
      - DEEPL_API_KEY
  
  json-watch:
    build: .
    command: watch /data
    volumes:
      - ${WATCH_FOLDER}:/data
    environment:
      - CF_ACCOUNT_ID
      - CF_D1_DATABASE_ID
      - R2_BUCKET_NAME
      - TG_CHAT_ID
