CREATE TABLE mail_documents (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    filename            TEXT NOT NULL,
    original_filename   TEXT NOT NULL,
    date                TEXT NOT NULL,
    issued              TEXT,
    sender              TEXT,
    reference           TEXT,
    type                TEXT,
    importance          INTEGER,
    amount              TEXT,
    deadline            TEXT,
    action_items        TEXT,
    summary_short       TEXT,
    ocr_confidence      INTEGER,
    deepl_score         INTEGER,
    claude_confidence   INTEGER,
    tokens_in           INTEGER,
    tokens_out          INTEGER,
    cost_usd            REAL,
    model               TEXT,
    schema_version      INTEGER NOT NULL DEFAULT 1,
    created_at          TEXT NOT NULL
);